### ISSUE TITLE
Добавить конфиг для линтера markdown

### ISSUE THREAD

**Issue by sashasushko** [htmlacademy/configs#5]
- Нужно сравнить пакеты [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) и [markdownlint](https://github.com/DavidAnson/markdownlint):
  - какой популярнее,
  - какой лучше поддерживают,
  - где больше возможностей,
  - где удобнее настройка,
  - где есть возможность переписать ли дописать пару правил,
  - где есть автофикс
- Выбрать "победителя"
- Добавить его базовый конфиг в репозиторий
- Описать в readme, как пользоваться
- Релизнуть

**Comment by levallevchenko** [comment]
Добавили https://github.com/htmlacademy/configs/commit/6f7ef6d349dd67c8e6d4058589c84acfcdbf6cdd
